/**
 * MicroIntern SG — 创始人手记与真实人情味微实习
 * "Get the Real Work Done. Impress the Company. Land the Offer."
 */

document.addEventListener('DOMContentLoaded', () => {

  // =========================================================================
  // 1. Dual Language Dictionary (100% Zero-Residue Translations)
  // =========================================================================

  const i18n = {
    en: {
      nav_brand_sub: "Singapore",
      nav_story: "The Story",
      nav_timeline: "How It Works",
      nav_cases: "Real Proofs",
      nav_cohort: "The Coffee Table",
      nav_join: "Join Cohort 01",

      hero_tag: "FOUNDER'S NOTE",
      hero_location: "Kent Ridge & Tanjong Pagar, Singapore",
      hero_line1: "The resume is dead.",
      hero_line2: "Get the real work done.",
      hero_intro: "In 2026, students use AI to generate flawless resumes, while corporate software filters 90% of applicants into the trash. We built MicroIntern SG to do the only thing that actually matters: let Singapore SMEs post 4-hour real tasks, and let students prove their competence with real output.",
      motto_main: "\"Get the Real Work Done. Impress the Company. Land the Offer.\"",
      motto_hand: "— the 3-step reality protocol",

      story_label: "FOUNDER'S MEMO",
      story_heading: "A Midnight Chat in Tanjong Pagar",
      story_p1: "A few weeks ago, at a coffee shop near Tanjong Pagar, an exhausted founder of a 20-person fintech SME sat down with an NUS Year 1 student. The founder had just spent 12 hours reading 240 resumes generated by ChatGPT. The student had just received his 45th automated rejection email saying: <em>\"We require candidates with prior corporate experience.\"</em>",
      story_p2: "Their WhatsApp conversation that evening captured everything broken about modern hiring — and the simple idea that fixes it:",
      
      chat_header_name: "Marcus (Founder, Fintech SME @ Tanjong Pagar)",
      chat_header_status: "Online",
      chat_m1: "\"I swear I'm losing my mind. Every resume claims they 'drove cross-functional strategic synergies', but when I interview them, they can't even write a basic cohort retention query.\"",
      chat_m2: "\"And on my side, I've spent all weekend building Python parsers and analyzing payment UX, but your ATS bot rejected my application in 4 seconds because my CV doesn't have '2 years prior internship'.\"",
      chat_m3: "\"Honestly? I don't care about your GPA or past titles. We have a 42% drop-off in our onboarding KYC flow right now. If someone can spend 3 hours analyzing our event log and show me where the leak is, I’d hire them on the spot.\"",
      chat_m4: "\"Send me the anonymized CSV. Give me Saturday afternoon. If my analysis solves your problem, we talk about an internship. If it doesn't, you keep the report and lose nothing.\"",
      chat_m5: "\"Deal. If it works, $150 honorarium + coffee this Thursday to sign your internship contract.\"",
      chat_t1: "11:14 PM",
      chat_t2: "11:16 PM",
      chat_t3: "11:19 PM",
      chat_t4: "11:22 PM",
      chat_t5: "11:24 PM",
      chat_note: "* That Saturday, Darren solved the leak. On Tuesday, he signed the contract.",
      story_p3: "That is a <strong>Micro-Internship</strong>. Not a three-month gamble. Not an AI resume-writing contest. A 4-hour business sprint where real capability is demonstrated and recognized.",

      timeline_label: "THE TIMELINE",
      timeline_heading: "The Timeline of a 4-Hour Micro-Internship",
      timeline_sub: "Here is how a real task flows from a founder's desk to a signed internship offer, without HR middlemen:",
      step1_time: "SATURDAY 2:00 PM",
      step1_title: "Claim a Focused 2–4 Hour Challenge",
      step1_desc: "SMEs don't post vague job specs. They post clear, scoped bottlenecks. For example: \"Parse 40 Malaysian hardware invoice PDFs into normalized JSON\" or \"Draft 3 native TikTok hooks for our coffee brand.\"",
      step2_time: "SATURDAY 5:30 PM",
      step2_title: "Submit Real Deliverables (Proof of Craft)",
      step2_desc: "No hypothetical cover letters. Students submit concrete deliverables: clean Python scripts with unit tests, structured teardown decks, or short-form video storyboards.",
      step3_time: "SUNDAY 10:00 AM",
      step3_title: "Founder Review & Direct Offer",
      step3_desc: "The founder opens the file. When they see thoughtful, clean execution, the hiring decision is obvious. The company pays the task honorarium and extends an immediate formal internship invitation.",

      cases_label: "CASE ARCHIVE",
      cases_heading: "Three Real Work Samples",
      cases_sub: "Inspect how three students without \"corporate pedigree\" secured direct offers by solving actual Singapore SME problems:",
      tab_c1: "PayBridge SEA (Fintech UX)",
      tab_c2: "OmniSupply AI (Python Data)",
      tab_c3: "KopiLabs SG (TikTok Content)",

      c1_sub: "Cross-border payments SME • Tanjong Pagar",
      c1_duration: "3.5 HOURS TASK",
      lbl_task: "THE FOUNDER'S BRIEF:",
      lbl_deliverable: "STUDENT WORK DELIVERED (DARREN, NUS YEAR 1):",
      c1_brief: "\"Our Singapore-to-Indonesia remittance app loses 42% of business users right at Singpass sync. Analyze 2,000 anonymized session logs and identify where the friction occurs.\"",
      c1_output: "<p><strong>Diagnosis:</strong> 68% of drop-offs were due to corporate entity-type mismatch with Singpass MyInfo for Business.</p><p><strong>Solution:</strong> Designed a fallback 1-click document upload with instant OCR verification.</p>",
      c1_outcome_author: "WhatsApp from Marcus (COO, PayBridge SEA):",
      c1_outcome_text: "\"Darren, your analysis was better than the external agency we paid $5,000 for. Are you free for coffee Thursday? We want you as our part-time Product Analyst.\"",

      c2_sub: "Supply chain automation • Jurong Innovation District",
      c2_duration: "4.0 HOURS TASK",
      lbl_deliverable_2: "STUDENT WORK DELIVERED (SIDDHARTH, NTU YEAR 1):",
      c2_brief: "\"We receive erratic invoice PDFs from 40 different Malaysian and Singaporean hardware vendors. Build a resilient Python regex script to parse SKU, quantity, and GST into clean JSON.\"",
      c2_output: "<p><strong>Architecture:</strong> Created a modular rule-based parser with fallback regex scoring. Wrote 15 unit tests covering edge-cases like handwritten GST annotations.</p>",
      c2_outcome_author: "WhatsApp from Elena (CTO, OmniSupply AI):",
      c2_outcome_text: "\"Siddharth, you didn't just solve it — you caught edge cases we didn't know existed. Sending over an internship contract for next semester right now.\"",

      c3_sub: "Heritage specialty coffee brand • Jalan Besar",
      c3_duration: "2.5 HOURS TASK",
      lbl_deliverable_3: "STUDENT WORK DELIVERED (CHERYL, SMU YEAR 1):",
      c3_brief: "\"We need 3 native TikTok script concepts to introduce traditional Nanyang roasting heritage to Gen Z coffee drinkers in Singapore and Malaysia.\"",
      c3_output: "<p><strong>Hook:</strong> 'Why your $8 iced latte is actually lying to your tastebuds (Singapore uncle approved).'</p><p><strong>Result:</strong> Brand ran test video; hit 340,000 views within 72 hours.</p>",
      c3_outcome_author: "WhatsApp from Kenji (Founder, KopiLabs SG):",
      c3_outcome_text: "\"Cheryl, you have more cultural pulse than any agency we spoke to. You're officially heading our content marketing.\"",

      cohort_label: "PILOT COHORT 01",
      cohort_heading: "The Coffee Table Cohort",
      cohort_sub: "We are not a massive automated hiring factory. For our inaugural Q4 pilot, we are personally sitting down with <strong>30 Singapore SME founders</strong> and <strong>100 NUS, NTU & SMU students</strong> to design and match your first micro-internship task.",
      form_role_lbl: "I AM JOINING AS:",
      role_sme_btn: "SME Founder / Lead",
      role_stu_btn: "University Student",
      form_name_lbl: "YOUR NAME / COMPANY NAME:",
      form_contact_lbl: "WHATSAPP OR EMAIL (FOR COFFEE INVITE):",
      form_field_lbl: "TASK OR STUDY DOMAIN:",
      form_submit_btn: "Reserve a Seat at the Coffee Table →",

      pass_header_txt: "MICROINTERN SG • PILOT VANGUARD",
      pass_lbl_registered: "REGISTERED TO:",
      pass_stamp_txt: "Verified for Singapore Pilot",
      pass_sig_txt: "Xiang & Founding Team",
      footer_brand: "MicroIntern.sg",
      footer_built: "Built with conviction at Kent Ridge & Tanjong Pagar.",
      footer_inquiry: "Inquiries:"
    },

    zh: {
      nav_brand_sub: "新加坡",
      nav_story: "手记故事",
      nav_timeline: "微实习流程",
      nav_cases: "真实成果交付",
      nav_cohort: "咖啡长桌计划",
      nav_join: "入驻首期试点",

      hero_tag: "创始人手记",
      hero_location: "新加坡 • 肯特岗与丹戎巴葛",
      hero_line1: "传统简历已经失效。",
      hero_line2: "搞定真实任务，直接说话。",
      hero_intro: "在 2026 年，学生用 AI 批量生成天衣无缝的简历，而企业的招聘软件直接将 90% 的申请丢进垃圾桶。我们创办 MicroIntern SG，只为促成一件真正有意义的事：让新加坡中小企业发布 4 小时的具体业务微任务，让大学生用看得见的真材实料证明自己的实力。",
      motto_main: "“搞定真实任务。赢得企业赞赏。直接斩获录用。”",
      motto_hand: "—— 3步真实闭环协议",

      story_label: "创始人手记 • 缘起",
      story_heading: "丹戎巴葛深夜的长谈",
      story_p1: "几周前，在新加坡丹戎巴葛附近的一家咖啡馆里，一位带着 20 人金融科技初创团队的老板，和一位刚进 NUS 的大一新生坐在一起。老板刚花了 12 个小时筛完 240 份用 ChatGPT 润色的水货简历；而学生则刚刚收到第 45 封冷冰冰的自动拒信：<em>“我们需要具备过往名企相关工作经验的候选人。”</em>",
      story_p2: "那天深夜他们在 WhatsApp 上的对话，道出了这个求职市场所有的荒诞——也给出了最质朴的解法：",

      chat_header_name: "Marcus（丹戎巴葛跨境支付初创团队创始人）",
      chat_header_status: "在线",
      chat_m1: "“我真快被逼疯了。每份简历都吹嘘自己‘推动了跨部门战略协同’，但真到了面试，连一个最基础的留存查询语句都写不出来。”",
      chat_m2: "“而对于我们学生来说，我整个周末都在写数据清洗脚本、拆解支付产品的用户体验，但你们公司的 HR 机器人只用了 4 秒就把我拒了，就因为我的简历上没有‘两年名企实习’。”",
      chat_m3: "“说实话，我根本不在乎你的 GPA 或虚假头衔。我们现在的跨境开户流程有 42% 的断崖式流失。如果有人能花 3 个小时分析我们的操作日志找出症结，我明天当场就录用他。”",
      chat_m4: "“把脱敏后的数据发我。给我周六一个下午。如果我的分析解决了你的痛点，我们聊实习；如果没解决，报告送你，你没有任何损失。”",
      chat_m5: "“成交。如果真管用，$150 任务津贴奉上，本周四直接喝咖啡签正式实习合同。”",
      chat_t1: "晚上 11:14",
      chat_t2: "晚上 11:16",
      chat_t3: "晚上 11:19",
      chat_t4: "晚上 11:22",
      chat_t5: "晚上 11:24",
      chat_note: "* 那个周六，Darren 找出了漏斗死角；周二，他签下了正式实习合同。",
      story_p3: "这就是<strong>微实习（Micro-Internship）</strong>。不是长达 3 个月的盲盒赌博，更不是 AI 包装简历大赛。一个 4 小时的真实业务冲刺，用实际成果让能力被看清、被赏识。",

      timeline_label: "运作流程",
      timeline_heading: "一次 4 小时微实习的时间轴",
      timeline_sub: "从创始人的桌案，到一份确定的实习 Offer，没有中间商的层层阻碍：",
      step1_time: "周六 下午 2:00",
      step1_title: "认领一个 2~4 小时的具体业务挑战",
      step1_desc: "企业不发布虚无缥缈的 JD，而是明确的业务痛点。例如：“将 40 家马来西亚供应商不同格式的 PDF 发票解析为标准 JSON”，或者“为我们的咖啡品牌写 3 组针对年轻人的短视频创意脚本”。",
      step2_time: "周六 下午 5:30",
      step2_title: "提交真实的成果交付物（以手艺说话）",
      step2_desc: "告别空谈的求职信。学生直接提交扎实成果：带有单元测试的代码、结构清晰的用户漏斗诊断报告、或者可落地的创意脚本。",
      step3_time: "周日 上午 10:00",
      step3_title: "创始人亲自检阅并直接发 Offer",
      step3_desc: "老板打开交付物，当看到扎实、严密、超越预期的执行力时，录用决策变得极其简单。企业当即发放任务津贴，并直接发出正式实习邀约。",

      cases_label: "实战交付档案",
      cases_heading: "3 份真实的成果交付样本",
      cases_sub: "看看 3 位原本在纸面上“毫无名企光环”的大一新生，如何通过解决具体的业务问题直接拿到 Offer：",
      tab_c1: "PayBridge SEA（金融科技 UX）",
      tab_c2: "OmniSupply AI（Python 数据脚本）",
      tab_c3: "KopiLabs SG（TikTok 爆款脚本）",

      c1_sub: "跨境支付中小企业 • 丹戎巴葛",
      c1_duration: "耗时 3.5 小时的微任务",
      lbl_task: "创始人的任务简报：",
      lbl_deliverable: "学生提交的实际交付物（Darren，NUS 大一）：",
      c1_brief: "“我们在用户提交 KYC 身份认证与完成首笔跨境汇款之间，存在 42% 的断崖流失。分析 2,000 条脱敏日志，找出流失阻力点并给出低代码优化方案。”",
      c1_output: "<p><strong>问题诊断：</strong>68% 的流失是因为企业在 Singpass 商业身份同步时，公司实体类型不匹配。</p><p><strong>优化方案：</strong>设计了带有即时 OCR 扫描预览的一键备用凭证上传通道。</p>",
      c1_outcome_author: "Marcus（PayBridge SEA 首席运营官）在 WhatsApp 上的回复：",
      c1_outcome_text: "“Darren，你做的这份诊断比我们花 5,000 新币请的外部咨询公司还要深入透彻。本周四有空喝杯咖啡吗？我们希望直接录用你为兼职产品分析师。”",

      c2_sub: "供应链自动化 SaaS • 裕廊创新区",
      c2_duration: "耗时 4.0 小时的微任务",
      lbl_deliverable_2: "学生提交的实际交付物（Siddharth，NTU 大一）：",
      c2_brief: "“我们每天收到 40 家不同供应商的 PDF 发票。编写一个基于 Python 正则的健壮脚本，准确解析 SKU、数量和税额为标准 JSON。”",
      c2_output: "<p><strong>架构设计：</strong>开发了模块化规则解析器并附带正则是错评分。编写了 15 个单元测试，覆盖了包含手写 GST 税额备注在内的所有死角。</p>",
      c2_outcome_author: "Elena（OmniSupply AI 首席技术官）在 WhatsApp 上的回复：",
      c2_outcome_text: "“Siddharth，你不仅搞定了需求，还测出了我们自己都不知道的发票排版死角。我现在就把下学期的正式实习合同发给你。”",

      c3_sub: "传统精品咖啡品牌 • 新加坡甘榜格南",
      c3_duration: "耗时 2.5 小时的微任务",
      lbl_deliverable_3: "学生提交的实际交付物（Cheryl，SMU 大一）：",
      c3_brief: "“我们需要 3 组在开头 2 秒抓住眼球的 TikTok 原生短视频脚本，将传统南洋咖啡烘焙历史传递给新马年轻一代客群。”",
      c3_output: "<p><strong>开头黄金抓手：</strong>‘为什么你花 8 新币买的冰拿铁正在欺骗你的味蕾（新加坡安哥实测认可）’。</p><p><strong>商业成效：</strong>品牌方实测上线该脚本，72 小时内自发播放量突破 34 万次。</p>",
      c3_outcome_author: "Kenji（KopiLabs SG 创始人）在 WhatsApp 上的回复：",
      c3_outcome_text: "“Cheryl，你的网感和对年轻受众的敏锐度比我们接触过的任何公关中介都要高得多。你现在全权负责我们品牌的内容营销。”",

      cohort_label: "首期先锋共创",
      cohort_heading: "咖啡长桌计划",
      cohort_sub: "我们不是冷冰冰的大型招聘工厂。在首期试点中，我们将亲自面对面坐下来，连接 <strong>30 位新加坡中小企业创始人</strong> 与 <strong>100 位来自 NUS / NTU / SMU 的在校学生</strong>，像朋友一样协助你们拆解并完成第一个微任务。",
      form_role_lbl: "我的加入身份：",
      role_sme_btn: "SME 创始人 / 业务主管",
      role_stu_btn: "高等院校在校学生",
      form_name_lbl: "您的姓名 / 企业名称：",
      form_contact_lbl: "WHATSAPP 或邮箱（方便约咖啡）：",
      form_field_lbl: "任务方向或专业领域：",
      form_submit_btn: "在咖啡长桌旁预留一个席位 →",

      pass_header_txt: "MICROINTERN SG • 试点先锋凭据",
      pass_lbl_registered: "登记人 / 机构：",
      pass_stamp_txt: "新加坡首期试点官方认证",
      pass_sig_txt: "Xiang 与创始团队",
      footer_brand: "MicroIntern.sg",
      footer_built: "诞生于新加坡肯特岗与丹戎巴葛。",
      footer_inquiry: "合作咨询："
    }
  };

  let currentLang = 'en';

  // =========================================================================
  // 2. Language Switcher Logic
  // =========================================================================

  const langToggleBtn = document.getElementById('lang-toggle-btn');
  const langLabel = document.getElementById('current-lang-label');

  function updatePageLanguage(lang) {
    currentLang = lang;
    document.body.setAttribute('data-lang', lang);
    document.documentElement.setAttribute('lang', lang);

    const dict = i18n[lang];
    if (!dict) return;

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key]) {
        el.innerHTML = dict[key];
      }
    });

    langLabel.textContent = lang === 'en' ? '中文 (ZH)' : 'English (EN)';
    localStorage.setItem('microintern_lang_v3', lang);
  }

  // Always check stored or default
  const savedLang = localStorage.getItem('microintern_lang_v3') || 'en';
  if (savedLang === 'zh') {
    updatePageLanguage('zh');
  }

  langToggleBtn.addEventListener('click', () => {
    const nextLang = currentLang === 'en' ? 'zh' : 'en';
    updatePageLanguage(nextLang);
    showToast(nextLang === 'en' ? 'Switched to English' : '已切换为纯中文手记');
  });


  // =========================================================================
  // 3. Case Selector Tabs
  // =========================================================================

  const caseBtns = document.querySelectorAll('.case-btn');
  const caseCards = document.querySelectorAll('.case-sample-card');

  caseBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const caseId = btn.getAttribute('data-case');

      caseBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      caseCards.forEach(c => c.classList.remove('active'));
      const target = document.getElementById(`${caseId}-card`);
      if (target) {
        target.classList.add('active');
      }
    });
  });


  // =========================================================================
  // 4. Coffee Table Form & Human Pass Generator
  // =========================================================================

  const coffeeForm = document.getElementById('coffee-form');
  const passResult = document.getElementById('pass-result');
  const passSerial = document.getElementById('pass-serial');
  const passHolder = document.getElementById('pass-holder');
  const passDetails = document.getElementById('pass-details');

  const roleRadios = document.querySelectorAll('input[name="userRole"]');
  const nameInput = document.getElementById('userName');

  roleRadios.forEach(radio => {
    radio.addEventListener('change', (e) => {
      const role = e.target.value;
      if (role === 'sme') {
        nameInput.placeholder = currentLang === 'zh' ? '例如：Marcus Tan 或 PayBridge SEA' : 'e.g. Marcus Tan or PayBridge SEA';
      } else {
        nameInput.placeholder = currentLang === 'zh' ? '例如：Darren Lim（NUS 大一）' : 'e.g. Darren Lim (NUS Year 1)';
      }
    });
  });

  coffeeForm.addEventListener('submit', (e) => {
    e.preventDefault();

    const role = document.querySelector('input[name="userRole"]:checked').value;
    const name = nameInput.value.trim();
    const field = document.getElementById('userField').value.trim();

    if (!name) return;

    const randNum = Math.floor(100 + Math.random() * 900);
    const prefix = role === 'sme' ? 'SG-FOUNDER' : 'SG-STUDENT';
    const serial = `#${prefix}-${randNum}`;

    passSerial.textContent = serial;
    passHolder.textContent = name;
    
    const roleText = role === 'sme' 
      ? (currentLang === 'zh' ? '新加坡 SME 创始人' : 'Singapore SME Founder')
      : (currentLang === 'zh' ? '高校高潜学子' : 'University Undergrad');
    
    passDetails.textContent = `${roleText} • ${field}`;

    passResult.style.display = 'block';
    passResult.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

    const toastMsg = currentLang === 'zh' 
      ? `已在咖啡长桌预留席位：${serial}` 
      : `Seat reserved at the Coffee Table: ${serial}`;
    showToast(toastMsg);
  });


  // =========================================================================
  // 5. Toast
  // =========================================================================

  const toast = document.getElementById('toast');
  const toastText = document.getElementById('toast-text');
  let toastTimeout = null;

  function showToast(msg) {
    if (toastTimeout) clearTimeout(toastTimeout);
    toastText.textContent = msg;
    toast.classList.add('show');
    toastTimeout = setTimeout(() => {
      toast.classList.remove('show');
    }, 2800);
  }

});
