/**
 * MicroIntern SG — 创始人手记（致企业与致学子的公开信）
 * "Get the Real Work Done. Impress the Company. Land the Offer."
 */

document.addEventListener('DOMContentLoaded', () => {

  // =========================================================================
  // 1. Dual Language Dictionary (Open Letters to Employers & Students)
  // =========================================================================

  const i18n = {
    en: {
      nav_brand_sub: "Singapore",
      nav_note: "Founder's Note",
      nav_timeline: "How It Works",
      nav_cases: "Real Proofs",
      nav_cohort: "The Coffee Table",
      nav_join: "Join Cohort 01",

      hero_tag: "FOUNDER'S NOTE",
      hero_location: "Kent Ridge & Tanjong Pagar, Singapore",
      hero_line1: "The resume is dead.",
      hero_line2: "Get the real work done.",
      hero_intro: "In 2026, students use AI to generate flawless resumes, while corporate software filters 90% of applicants into the trash. We built MicroIntern SG to do the only thing that actually matters: let Singapore SMEs post 4-hour real tasks, and let students prove their competence with real output.",
      motto_main: "\"Get the Real Work Done. Impress the Company. Land the Offer.\"",
      motto_hand: "— the 3-step reality protocol",

      note_label: "A LETTER FROM THE FOUNDER",
      
      // Memo 1: To Employers
      note_sme_title: "To the Singapore SME Founder & HR: Are You Sick of ChatGPT-Generated Resumes Yet?",
      note_sme_body: "<p>If you run a business in Singapore, you know the sinking feeling. You post an internship opening, and within 48 hours you are buried in 200 resumes. Every single one is formatted identically, packed with polished buzzwords generated by large language models, and claims they 'spearheaded cross-functional synergies'.</p><p>You spend precious evenings filtering them. You shortlist five, interview them, and extend an offer — only to discover in week three that they freeze when asked to write a clean database query, troubleshoot a payment drop-off, or draft an authentic customer email. You just burned two months of intern salary and dozens of hours of your team’s focus on a piece of paper.</p><p class='essay-quote-highlight'>\"You don't hire a chef by reading their essay about culinary theory. You taste their soup. MicroIntern gives you the soup before you sign the contract.\"</p>",

      // Memo 2: To Students
      note_stu_title: "To the Singapore Undergrad: Tired of Being Rejected for \"Lacking Experience\"?",
      note_stu_body: "<p>And if you are an undergraduate at NUS, NTU, or SMU, you know the other side of this absurd circus. You are hungry to work. You spend your weekends learning real skills, writing code, and analyzing products. But every 'entry-level' job portal slams the door in your face: <em>'Requires 1–2 prior internships and 2+ years of relevant industry experience.'</em></p><p>How are you supposed to get your first internship if every company requires you to already have one? You send out 60 cold applications with a template resume, only to be rejected in four seconds by an automated keyword bot. It is insulting, exhausting, and completely disconnected from actual ability.</p>",

      // Memo 3: The Solution
      note_solution_title: "The Solution: 4 Hours of Real Work, Recognized and Rewarded.",
      note_solution_body: "<p>We started MicroIntern SG because both sides deserve better.</p><p>Instead of asking students to write resumes, we ask Singapore SMEs to post a self-contained 2–4 hour business challenge. Instead of screening applicants with keywords, founders inspect actual deliverables. If a student's output solves your problem, you hire them with 100% conviction. If it doesn't, you keep the report, pay a small honorarium, and lose zero time.</p><p><strong>No recruitment agencies. No AI resume arms race. Just proof of work.</strong></p>",

      // Timeline
      timeline_label: "THE TIMELINE",
      timeline_heading: "How a 4-Hour Micro-Internship Actually Works",
      timeline_sub: "Here is how a real task flows from a founder's desk to a signed internship offer, without HR middlemen:",
      step1_time: "SATURDAY 2:00 PM",
      step1_title: "Claim a Focused 2–4 Hour Challenge",
      step1_desc: "SMEs don't post vague job specs. They post clear, scoped bottlenecks. For example: \"Parse 40 Malaysian hardware invoice PDFs into normalized JSON\" or \"Draft 3 native TikTok hooks for our coffee brand.\"",
      step2_time: "SATURDAY 5:30 PM",
      step2_title: "Submit Real Deliverables (Proof of Craft)",
      step2_desc: "No hypothetical cover letters. Students submit concrete deliverables: clean Python scripts with unit tests, structured teardown decks, or short-form video storyboards.",
      step3_time: "SUNDAY 10:00 AM",
      step3_title: "Founder Review & Direct Offer",
      step3_desc: "The founder opens the file. When they see thoughtful, clean execution, the hiring decision is obvious. The company pays the task honorarium and extends an immediate formal internship invitation.",

      // Cases
      cases_label: "CASE ARCHIVE",
      cases_heading: "Three Real Work Samples",
      cases_sub: "Inspect how three students without \"corporate pedigree\" secured direct offers by solving actual Singapore SME problems:",
      tab_c1: "PayBridge SEA (Fintech UX)",
      tab_c2: "OmniSupply AI (Python Data)",
      tab_c3: "KopiLabs SG (TikTok Content)",

      c1_sub: "Cross-border payments SME • Tanjong Pagar",
      c1_duration: "3.5 HOURS TASK",
      lbl_task: "THE FOUNDER'S BRIEF:",
      lbl_deliverable: "STUDENT WORK DELIVERED (DARREN, NUS YEAR 1):",
      c1_brief: "\"Our Singapore-to-Indonesia remittance app loses 42% of business users right at Singpass sync. Analyze 2,000 anonymized session logs and identify where the friction occurs.\"",
      c1_output: "<p><strong>Diagnosis:</strong> 68% of drop-offs were due to corporate entity-type mismatch with Singpass MyInfo for Business.</p><p><strong>Solution:</strong> Designed a fallback 1-click document upload with instant OCR verification.</p>",
      c1_outcome_author: "Feedback from Marcus (COO, PayBridge SEA):",
      c1_outcome_text: "\"Darren, your analysis was better than the external agency we paid $5,000 for. We offered him our part-time Product Analyst internship within 48 hours.\"",

      c2_sub: "Supply chain automation • Jurong Innovation District",
      c2_duration: "4.0 HOURS TASK",
      lbl_deliverable_2: "STUDENT WORK DELIVERED (SIDDHARTH, NTU YEAR 1):",
      c2_brief: "\"We receive erratic invoice PDFs from 40 different Malaysian and Singaporean hardware vendors. Build a resilient Python regex script to parse SKU, quantity, and GST into clean JSON.\"",
      c2_output: "<p><strong>Architecture:</strong> Created a modular rule-based parser with fallback regex scoring. Wrote 15 unit tests covering edge-cases like handwritten GST annotations.</p>",
      c2_outcome_author: "Feedback from Elena (CTO, OmniSupply AI):",
      c2_outcome_text: "\"Siddharth caught edge cases we didn't know existed. We sent over an internship contract for next semester immediately.\"",

      c3_sub: "Heritage specialty coffee brand • Jalan Besar",
      c3_duration: "2.5 HOURS TASK",
      lbl_deliverable_3: "STUDENT WORK DELIVERED (CHERYL, SMU YEAR 1):",
      c3_brief: "\"We need 3 native TikTok script concepts to introduce traditional Nanyang roasting heritage to Gen Z coffee drinkers in Singapore and Malaysia.\"",
      c3_output: "<p><strong>Hook:</strong> 'Why your $8 iced latte is actually lying to your tastebuds (Singapore uncle approved).'</p><p><strong>Result:</strong> Brand ran test video; hit 340,000 views within 72 hours.</p>",
      c3_outcome_author: "Feedback from Kenji (Founder, KopiLabs SG):",
      c3_outcome_text: "\"Cheryl produced 3 killer concepts in an afternoon. She is now heading our content marketing.\"",

      // Cohort
      cohort_label: "PILOT COHORT 01",
      cohort_heading: "The Coffee Table Cohort",
      cohort_sub: "We are not a massive automated hiring factory. For our inaugural Q4 pilot, we are personally sitting down with <strong>30 Singapore SME founders</strong> and <strong>100 NUS, NTU & SMU students</strong> to design and match your first micro-internship task.",
      form_role_lbl: "I AM JOINING AS:",
      role_sme_btn: "SME Founder / Lead",
      role_stu_btn: "University Student",
      form_name_lbl: "YOUR NAME / COMPANY NAME:",
      form_contact_lbl: "WHATSAPP OR EMAIL (FOR COFFEE INVITE):",
      form_field_lbl: "TASK OR STUDY DOMAIN:",
      form_submit_btn: "Reserve a Seat at the Coffee Table →",

      pass_header_txt: "MICROINTERN SG • PILOT VANGUARD",
      pass_lbl_registered: "REGISTERED TO:",
      pass_stamp_txt: "Verified for Singapore Pilot",
      pass_sig_txt: "Xiang & Founding Team",
      footer_brand: "MicroIntern.sg",
      footer_built: "Built with conviction at Kent Ridge & Tanjong Pagar.",
      footer_inquiry: "Inquiries:"
    },

    zh: {
      nav_brand_sub: "新加坡",
      nav_note: "创始人手记",
      nav_timeline: "微实习流程",
      nav_cases: "真实成果交付",
      nav_cohort: "咖啡长桌计划",
      nav_join: "入驻首期试点",

      hero_tag: "创始人手记",
      hero_location: "新加坡 • 肯特岗与丹戎巴葛",
      hero_line1: "传统简历已经失效。",
      hero_line2: "搞定真实任务，直接说话。",
      hero_intro: "在 2026 年，学生用 AI 批量生成天衣无缝的简历，而企业的招聘软件直接将 90% 的申请丢进垃圾桶。我们创办 MicroIntern SG，只为促成一件真正有意义的事：让新加坡中小企业发布 4 小时的具体业务微任务，让大学生用看得见的真材实料证明自己的实力。",
      motto_main: "“搞定真实任务。赢得企业赞赏。直接斩获录用。”",
      motto_hand: "—— 3步真实闭环协议",

      note_label: "一封来自创始人的公开信",

      // Memo 1: 致企业主与 HR
      note_sme_title: "致新加坡企业主与 HR：你是否已经被 GPT 批量生产的假简历烦透了？",
      note_sme_body: "<p>如果你在新加坡经营一家成长中的中小企业，你一定体会过那种深深的无力感。你在求职网站上发布一个实习岗位，不到 48 小时，邮箱就被 200 份简历淹没。每一份的排版都惊人一致，通篇都是大语言模型润色出来的漂亮八股文，人人都自称“推动了跨部门战略协同与业务赋能”。</p><p>你牺牲宝贵的下班时间一份份初筛，挑了 5 个人面试，发了 Offer——结果入职到第三周你才绝望地发现，面对真实的业务场景，他们连一行干净的数据库查询都写不出，连一个支付流失漏斗都拆不清，脱离了 AI 提示词甚至写不出一封得体的客户邮件。你为了几张纸面简历，白白烧掉了两个月的实习工资和资深员工宝贵的带教精力。</p><p class='essay-quote-highlight'>“招厨师从来不需要他写一万字的美食理论论文，你尝一口他熬的汤就全明白了。微实习让你在签约发 Offer 之前，先尝到那口真材实料的汤。”</p>",

      // Memo 2: 致学子
      note_stu_title: "致新加坡高校学子：你是否也对“必须有经验才能找经验”感到愤怒？",
      note_stu_body: "<p>而如果你是来自 NUS、NTU 或 SMU 的在校大学生，你一定经历过求职系统另一端的荒谬与碰壁。你满怀热忱，周末熬夜学技术、啃业务、写代码，然而每次满怀希望地点开所谓“初级岗位”，迎面砸来的都是同一行冰冷的门槛：<em>“要求 1~2 段过往名企相关实习经历，以及 2 年以上行业实战经验。”</em></p><p>如果每一家公司都要求你“必须先有实习经历”，大一新生和年轻学子的第一段经验到底该从何而来？你认认真真投了 60 家公司，却在 4 秒钟内被企业的 ATS 关键词过滤机器人无情淘汰丢进垃圾桶。这不仅令人精疲力竭，更是对真实能力的侮辱。</p>",

      // Memo 3: 解法
      note_solution_title: "破局之道：4 小时真实微任务，用扎实交付换取确定的 Offer。",
      note_solution_body: "<p>我们创办 MicroIntern SG，就是为了让企业和学生彻底摆脱这套两头受害的死循环。</p><p>我们不再要求学生写虚头巴脑的简历，而是让新加坡本地企业发布一个 2~4 小时内可以完成的具体业务痛点微任务。企业不再对着关键词猜人，而是直接验收实际交付物。只要学生的解决方案扎实严密，你当场就能 100% 放心发 Offer；即便最终没有录用，企业也保留了这份工作成果，学生拿到了津贴，双方零试错风险。</p><p><strong>没有猎头中介抽成。没有 AI 简历军备竞赛。只有看得见的工作量证明。</strong></p>",

      // Timeline
      timeline_label: "运作流程",
      timeline_heading: "一次 4 小时微实习的真实全貌",
      timeline_sub: "从创始人的桌案，到一份确定的实习 Offer，没有中间商的层层阻碍：",
      step1_time: "周六 下午 2:00",
      step1_title: "认领一个 2~4 小时的具体业务挑战",
      step1_desc: "企业不发布虚无缥缈的 JD，而是明确的业务痛点。例如：“将 40 家供应商不同格式的 PDF 发票解析为标准 JSON”，或者“为本地咖啡品牌策划 3 组针对年轻客群的短视频创意脚本”。",
      step2_time: "周六 下午 5:30",
      step2_title: "提交真实的成果交付物（以手艺说话）",
      step2_desc: "告别空谈的求职信。学生直接提交扎实成果：带有单元测试的代码、结构清晰的用户漏斗诊断报告、或者可落地的创意脚本。",
      step3_time: "周日 上午 10:00",
      step3_title: "创始人亲自检阅并直接发 Offer",
      step3_desc: "老板打开交付物，当看到扎实、严密、超越预期的执行力时，录用决策变得极其简单。企业当即发放任务津贴，并直接发出正式实习邀约。",

      // Cases
      cases_label: "实战交付档案",
      cases_heading: "3 份真实的成果交付样本",
      cases_sub: "看看 3 位原本在纸面上“毫无名企光环”的大一新生，如何通过解决具体的业务问题直接拿到 Offer：",
      tab_c1: "PayBridge SEA（金融科技 UX）",
      tab_c2: "OmniSupply AI（Python 数据脚本）",
      tab_c3: "KopiLabs SG（TikTok 爆款脚本）",

      c1_sub: "跨境支付中小企业 • 丹戎巴葛",
      c1_duration: "耗时 3.5 小时的微任务",
      lbl_task: "创始人的任务简报：",
      lbl_deliverable: "学生提交的实际交付物（Darren，NUS 大一）：",
      c1_brief: "“我们在用户提交 KYC 身份认证与完成首笔跨境汇款之间，存在 42% 的断崖流失。分析 2,000 条脱敏日志，找出流失阻力点并给出低代码优化方案。”",
      c1_output: "<p><strong>问题诊断：</strong>68% 的流失是因为企业在 Singpass 商业身份同步时，公司实体类型不匹配。</p><p><strong>优化方案：</strong>设计了带有即时 OCR 扫描预览的一键备用凭证上传通道。</p>",
      c1_outcome_author: "Marcus（PayBridge SEA 首席运营官）的评价反馈：",
      c1_outcome_text: "“Darren 做出的这份诊断报告，比我们之前花 5,000 新币请的外部咨询公司还要扎实透彻。我们在检阅完交付物的 48 小时内，直接发了兼职产品分析师 Offer。”",

      c2_sub: "供应链自动化 SaaS • 裕廊创新区",
      c2_duration: "耗时 4.0 小时的微任务",
      lbl_deliverable_2: "学生提交的实际交付物（Siddharth，NTU 大一）：",
      c2_brief: "“我们每天收到 40 家不同供应商的 PDF 发票。编写一个基于 Python 正则的健壮脚本，准确解析 SKU、数量和税额为标准 JSON。”",
      c2_output: "<p><strong>架构设计：</strong>开发了模块化规则解析器并附带正则是错评分。编写了 15 个单元测试，覆盖了包含手写 GST 税额备注在内的所有死角。</p>",
      c2_outcome_author: "Elena（OmniSupply AI 首席技术官）的评价反馈：",
      c2_outcome_text: "“Siddharth 不仅解决了问题，还测出了我们自己都不知道的发票死角。我们当场把下学期的正式实习合同发给了他。”",

      c3_sub: "传统精品咖啡品牌 • 新加坡甘榜格南",
      c3_duration: "耗时 2.5 小时的微任务",
      lbl_deliverable_3: "学生提交的实际交付物（Cheryl，SMU 大一）：",
      c3_brief: "“我们需要 3 组在开头 2 秒抓住眼球的 TikTok 原生短视频脚本，将传统南洋咖啡烘焙历史传递给新马年轻一代客群。”",
      c3_output: "<p><strong>开头黄金抓手：</strong>‘为什么你花 8 新币买的冰拿铁正在欺骗你的味蕾（新加坡安哥实测认可）’。</p><p><strong>商业成效：</strong>品牌方实测上线该脚本，72 小时内自发播放量突破 34 万次。</p>",
      c3_outcome_author: "Kenji（KopiLabs SG 创始人）的评价反馈：",
      c3_outcome_text: "“Cheryl 一个下午搞出的创意脚本比任何公关中介都更有网感。她现在全权负责我们品牌的内容营销。”",

      cohort_label: "首期先锋共创",
      cohort_heading: "咖啡长桌计划",
      cohort_sub: "我们不是冷冰冰的大型招聘工厂。在首期试点中，我们将亲自面对面坐下来，连接 <strong>30 位新加坡中小企业创始人</strong> 与 <strong>100 位来自 NUS / NTU / SMU 的在校学生</strong>，像朋友一样协助你们拆解并完成第一个微任务。",
      form_role_lbl: "我的加入身份：",
      role_sme_btn: "SME 创始人 / 业务主管",
      role_stu_btn: "高等院校在校学生",
      form_name_lbl: "您的姓名 / 企业名称：",
      form_contact_lbl: "WHATSAPP 或邮箱（方便约咖啡）：",
      form_field_lbl: "任务方向或专业领域：",
      form_submit_btn: "在咖啡长桌旁预留一个席位 →",

      pass_header_txt: "MICROINTERN SG • 试点先锋凭据",
      pass_lbl_registered: "登记人 / 机构：",
      pass_stamp_txt: "新加坡首期试点官方认证",
      pass_sig_txt: "Xiang 与创始团队",
      footer_brand: "MicroIntern.sg",
      footer_built: "诞生于新加坡肯特岗与丹戎巴葛。",
      footer_inquiry: "合作咨询："
    }
  };

  let currentLang = 'en';

  // =========================================================================
  // 2. Language Switcher Logic
  // =========================================================================

  const langToggleBtn = document.getElementById('lang-toggle-btn');
  const langLabel = document.getElementById('current-lang-label');

  function updatePageLanguage(lang) {
    currentLang = lang;
    document.body.setAttribute('data-lang', lang);
    document.documentElement.setAttribute('lang', lang);

    const dict = i18n[lang];
    if (!dict) return;

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key]) {
        el.innerHTML = dict[key];
      }
    });

    langLabel.textContent = lang === 'en' ? '中文 (ZH)' : 'English (EN)';
    localStorage.setItem('microintern_lang_v4', lang);
  }

  const savedLang = localStorage.getItem('microintern_lang_v4') || 'en';
  if (savedLang === 'zh') {
    updatePageLanguage('zh');
  }

  langToggleBtn.addEventListener('click', () => {
    const nextLang = currentLang === 'en' ? 'zh' : 'en';
    updatePageLanguage(nextLang);
    showToast(nextLang === 'en' ? 'Switched to English' : '已切换为中文手记');
  });


  // =========================================================================
  // 3. Case Selector Tabs
  // =========================================================================

  const caseBtns = document.querySelectorAll('.case-btn');
  const caseCards = document.querySelectorAll('.case-sample-card');

  caseBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const caseId = btn.getAttribute('data-case');

      caseBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      caseCards.forEach(c => c.classList.remove('active'));
      const target = document.getElementById(`${caseId}-card`);
      if (target) {
        target.classList.add('active');
      }
    });
  });


  // =========================================================================
  // 4. Coffee Table Form & Human Pass Generator
  // =========================================================================

  const coffeeForm = document.getElementById('coffee-form');
  const passResult = document.getElementById('pass-result');
  const passSerial = document.getElementById('pass-serial');
  const passHolder = document.getElementById('pass-holder');
  const passDetails = document.getElementById('pass-details');

  const roleRadios = document.querySelectorAll('input[name="userRole"]');
  const nameInput = document.getElementById('userName');

  roleRadios.forEach(radio => {
    radio.addEventListener('change', (e) => {
      const role = e.target.value;
      if (role === 'sme') {
        nameInput.placeholder = currentLang === 'zh' ? '例如：Marcus Tan 或 PayBridge SEA' : 'e.g. Marcus Tan or PayBridge SEA';
      } else {
        nameInput.placeholder = currentLang === 'zh' ? '例如：Darren Lim（NUS 大一）' : 'e.g. Darren Lim (NUS Year 1)';
      }
    });
  });

  coffeeForm.addEventListener('submit', (e) => {
    e.preventDefault();

    const role = document.querySelector('input[name="userRole"]:checked').value;
    const name = nameInput.value.trim();
    const field = document.getElementById('userField').value.trim();

    if (!name) return;

    const randNum = Math.floor(100 + Math.random() * 900);
    const prefix = role === 'sme' ? 'SG-FOUNDER' : 'SG-STUDENT';
    const serial = `#${prefix}-${randNum}`;

    passSerial.textContent = serial;
    passHolder.textContent = name;
    
    const roleText = role === 'sme' 
      ? (currentLang === 'zh' ? '新加坡 SME 创始人' : 'Singapore SME Founder')
      : (currentLang === 'zh' ? '高校高潜学子' : 'University Undergrad');
    
    passDetails.textContent = `${roleText} • ${field}`;

    passResult.style.display = 'block';
    passResult.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

    const toastMsg = currentLang === 'zh' 
      ? `已在咖啡长桌预留席位：${serial}` 
      : `Seat reserved at the Coffee Table: ${serial}`;
    showToast(toastMsg);
  });


  // =========================================================================
  // 5. Toast
  // =========================================================================

  const toast = document.getElementById('toast');
  const toastText = document.getElementById('toast-text');
  let toastTimeout = null;

  function showToast(msg) {
    if (toastTimeout) clearTimeout(toastTimeout);
    toastText.textContent = msg;
    toast.classList.add('show');
    toastTimeout = setTimeout(() => {
      toast.classList.remove('show');
    }, 2800);
  }

});
